In [1]:
import numpy as np # para usar arreglos
import sklearn # para el algoritmo clasificador
from sklearn.datasets import load_iris #carga el set de datos de iris de sklearn
from sklearn.model_selection import train_test_split #divide el set de datos en entrenamieto y testing

In [2]:
iris=load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [4]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
#iris['data']

In [6]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(iris['data'],iris['target'])

In [9]:
X_train.shape
y_train.shape

(112,)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')

In [11]:
knn.score(X_test,y_test)

1.0

In [12]:
knn.predict([[6.2,1.4,5.6,1.1]])

array([2])

In [13]:
knn.predict([[1.2,2.4,2.6,1.1]])

array([0])

In [14]:
knn.predict([[6.2,5.4,1.5,6.1]])

array([2])

In [15]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')